### PR TITLE
Nov 2018 MCA updates (-punc +Word)

### PR DESCRIPTION
**Pull request by soupman98**
Nov 2018 MCA updates redone to meet punctuation and capitalization guidelines. 
Also ran doc (copies) thru Word to find and trap additional errors.

### CODE REVIEW

**Comment by waltermyersiii** [comment]
We have some merge conflicts, Steve.

**Comment by DawnmarieDesJardins** [comment]
I still need to QC this one before we merge.

**Comment by soupman98** [comment]
FYI,
I ran the docs (via copy) thru Word Spell and Grammar check this time and found a lot of spelling and punctuation errors that were overlooked/missed manually last time around.
Mostly in the Add’l Text for images.

**Comment by DawnmarieDesJardins** [comment]
@soupman98 
Hi Steve,
Sorry, I didn't mean to confuse you.  I put the QC comment on there so no one would merge before I have a chance to look through the changes.  I am not able to resolve merge conflicts so please take a look at that and let me know when you're ready for my QC pass.

**Comment by soupman98** [comment]
It should all be ready as of yesterday when I put in a PR.

**Comment by soupman98** [comment]
All, I believe these 4 conflicts to be remediated now. Thanks.

**Pull request closed without merging**
