### PR TITLE
MCW MCA NOV 2018

### PR DESCRIPTION
**Pull request by soupman98**
HOL/Setup Guides
- Various grammar, punctuation and capitalization fixes and updates
- Task 5 (PDF automation) changes to Azure UX reflected
- CORS configuration guidance changed
- Logic App guidance updated (Logic Designer changes)
Trainer PPT
- Minor layout, punctuation and grammar fixes

### CODE REVIEW

**Comment by waltermyersiii** [comment]
Soupman, we won't accept PRs unless a member. Can you identify yourself?

**Comment by soupman98** [comment]
Hello,
I’m relatively new with Solliance. We’re still working out my access and credentials and such.
I’ve copied Dan Patrick who’s been working with me.

Thanks for the quick followup.

Also my Solliance email is Steve@Solliance.net


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by waltermyersiii** [comment]
Just sent you an invite to join as a collaborator.

**Comment by soupman98** [comment]
Closing this PR to open a new one.

**Pull request closed without merging**
