### PR TITLE
March 2019 - scheduled content update 

### PR DESCRIPTION
**Pull request by timahenning**
References #31

### CODE REVIEW

**Comment by karlitoz007** [comment]
I took a look at https://github.com/Microsoft/MCW-Modern-cloud-apps/pull/32/files and everything looks fine.

**Comment by DawnmarieDesJardins** [comment]
@timhenning @ZoinerTejada 
Hello,
Leads have signed off on this update.  Please finalize the workshop and close any outstanding issues.  Assign to me when it's ready for QC/merge.
Thanks, Dawnmarie

**Comment by timahenning** [comment]
Updated the content to reference Visual Studio 2019. Reference #31

**Comment by timahenning** [comment]
Hey Dawnmarie,

I have merged the Visual Studio 2019 changes into master.  Unfortunately, I cannot assign the pull request to you.  Still don’t have the permissions in Git to assign requests.  Is there something I need to set on my end?

Tim

**Pull request merged**
